### ISSUE TITLE
Add a redirect from sweetfarm.org/sponsorananimal to sweetfarm.org/sponsor

### ISSUE THREAD

**Issue by ksegev** [sweetfarm/backlog#14]
Add a redirect from sweetfarm.org/sponsorananimal to sweetfarm.org/sponsor

The animal sponsor program was originally _sweetfarm.org/sponsorananimal_ and ive shortened it to _sweetfarm.org/sponsor_

When you go to sweetfarm.org/sponsorananimal you get a dead end

Thanks!

**Comment by azoff** [comment]
Done: https://sweetfarm.org/sponsorananimal
