### ISSUE TITLE
Update the "impact.sweetfarm.org" vanity URL

### ISSUE THREAD

**Issue by ksegev** [sweetfarm/backlog#15]
Network For Good is live! Can you please revert "impact.sweetfarm.org" to https://sweetfarm.networkforgood.com/projects/48399-sweet-farm-annual-fund at your earliest?

can you also add these redirects to the same page:

-impact.sweetfarm.com
-sweetfarm.org/impact
-sweetfarm.com/impact
-sweetfarm.org/donate
-sweetfarm.com/donate
-sweetfarm.org/support
-sweetfarm.com/support

TY!

**Comment by azoff** [comment]
the paths (e.g. sweetfarm.org/donate) are set up. The subdomain though (impact.sweetfarm.org) is not working correctly and we'll need networkforgood.com to play ball with us in order for it to work.
