### ISSUE TITLE
create new email alias: tours@sweetfarm.org

### ISSUE THREAD

**Issue by ksegev** [sweetfarm/backlog#17]
Please set up new sweet farm email alias: tours@sweetfarm.org 

Please make it so these messages get directed to the following peoples inboxes: Nate, Kaylan, Penny, Kristina

If it's a best / common practice to create a number of them, i'd also add: 
- tours@sweetfarm.com 
- tour@sweetfarm.org 
- tour@sweetfarm.com

**Comment by azoff** [comment]
Created tours, I'll leave the other one to you!
